# -*- coding: utf-8 -*-
"""function_lambda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KfM6Tr4Ha0DmOi9qT647ORO6e-6NqIne
"""

def my_function():
  print("within a function")

my_function()

def calculat_sum(a,b):
  return a+b

print(calculat_sum(4,5))

def calculat_sum_multiplication(a,b):
  return a+b, a*b

var_sum,var_mult = calculat_sum_multiplication(10,3)

print(var_sum)
print(var_mult)

my_var = lambda x : x +100

print(my_var(10))

my_var = lambda a,b : a+b

print(my_var(4,5))

